version: '3.8'

services:
  db:
    container_name: postgres
    build:
      context: ./infra
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'

  backend:
    build: ./api
    container_name: back
    env_file:
      - ./api/.env
    depends_on:
      - db
    ports:
      - "8100:8100"

  frontend:
    build: ./web
    container_name: front
    env_file:
      - ./web/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
